core/urls.py
from django.urls import path

from core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

inscricoes/urls.py
from django.urls import path


from inscricoes import views as v

app_name = 'inscricoes'


urlpatterns = [
    path('', v.InscricaoList.as_view(), name='produto_list'),
    path('listpdf/', v.GeneratePDF.as_view(), name='list_pdf'),
    path('List_pdf_debug', v.PdfDebug.as_view(), name='List_pdf_debug'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('<int:pk>/upload/', v.Upload.as_view(), name='upload'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('add2/', v.produto_add, name='produto_add2'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/nota/', v.ProdutoNotaUpdate.as_view(), name='produto_edit_nota'),

    path('<int:pk>/json/', v.produto_json, name='produto_json'),

    path('avisolista', v.ListaAvisosView.as_view(), name='aviso_list'),
    path('aviso_add/', v.AvisoCreate.as_view(), name='aviso_add'),
    path('<int:pk>/edit_aviso/', v.AvisoUpdate.as_view(), name='aviso_edit'),
    path('avisolista2', v.ListaAvisosView2.as_view(), name='aviso_list2'),

]

inscricoes_ex/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

inscricoes/models.py
from django.db import models
from django.urls import reverse_lazy




class Inscricao(models.Model):
    nome = models.CharField('Nome', max_length=100)
    email = models.EmailField()
    cpf = models.CharField(u'CPF', max_length=20)
    telefone = models.CharField(max_length=100, unique=False)
    endereco = models.CharField(max_length=100, unique=False)
    numero = models.DecimalField('numero', max_digits=7, decimal_places=2)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField('cep', max_length=10, null=True, blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
    nota = models.DecimalField(u'Valor Médio', max_digits=20, decimal_places=2, null=True, blank=True)
    upload = models.FileField(upload_to='upload', null=True, blank=True)


    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse_lazy('inscricoes:produto_detail', kwargs={'pk': self.pk})


class FimInscricoes(models.Model):
    aviso = models.TextField()
    fim_inscricao = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse_lazy('inscricoes:aviso_list')

inscricoes/forms.py
from django import forms

from .models import Inscricao, FimInscricoes


class InscricaoForm(forms.ModelForm):

    class Meta:
        model = Inscricao
        fields = 'nome','cpf', 'email', 'telefone', 'endereco', 'numero', 'cidade', 'estado', 'cep', 'data_nascimento', 'upload',


class InscricaoNotaForm(forms.ModelForm):

    class Meta:
        model = Inscricao
        fields = 'nome','cpf', 'email', 'telefone', 'endereco', 'numero', 'cidade', 'estado', 'cep', 'data_nascimento', 'nota', 'upload',


class DocumentoForm(forms.ModelForm):

    class Meta:
        model = Inscricao
        fields = 'upload',


class AvisoForm(forms.ModelForm):

    class Meta:
        model = FimInscricoes
        fields = 'aviso','fim_inscricao',

inscricoes/views.py
from io import BytesIO
from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa
from django.db.models import Q, Count
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, View, TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import InscricaoForm, InscricaoNotaForm, AvisoForm
from .models import Inscricao, FimInscricoes


@login_required(login_url='login/')
def home(request):
    return render(request, 'produto_list.html')

@login_required(login_url='login/')
def produto_list(request):
    template_name = 'produto_list.html'
    objects = Inscricao.objects.order_by("id").all()
    count = Inscricao.bjects.values("cpf").annotate(Count("id"))
    contador = {'count': count}

    search = request.GET.get('search')
    if search:
        objects = objects.filter(nome__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context, contador)

class InscricaoList(ListView):
    model = Inscricao
    template_name = 'produto_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super(InscricaoList, self).get_queryset()
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(
                Q(nome__icontains=search) |
                Q(cpf__icontains=search)
            )
        return queryset

class ListaInscritosListView(ListView):
    model = Inscricao
    template_name = 'produto_list.html'
    context_object_name = 'inscritos'

'''PDF'''

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


class GeneratePdf(View):

    def get(self, request, *args, **kwargs):
        data = Inscricao.objects.all()
        pdf = render_to_pdf('list_pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')



class GeneratePDF(View):

    def get(self, request, *args, **kwargs):
        object = Inscricao.objects.all()
        dados = {
            'object_list': object,
        }
        template = get_template('list_pdf.html')

        html = template.render(dados)
        pdf = render_to_pdf('list_pdf.html', dados)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")



"""class GerarPDFMixin:
    def render_to_pdf(self, template_end, context_dict={}):
        template = get_template(template_end)
        html = template.render(context_dict)
        result = BytesIO()
        try:
            pdf = pisa.pisaDocument(BytesIO(html.encode("")), result)
            return HttpResponse(result.getvalue(), context_type='application/pdf')
        except Exception as e:
            print(e)
            return None
class ProdutoListPdfView(View, GerarPDFMixin):
    def get(self, request, *args, **kwargs):
        inscritos = Produto.objects.all()
        dados = {
            'inscritos': inscritos,
        }
        pdf = GerarPDFMixin()
        return pdf.render_to_pdf('list_pdf.html', dados)"""



def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Inscricao.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request):
    form = InscricaoForm(request.POST or None)
    template_name = 'produto_form2.html'

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inscricao:produto_list'))

    context = {'form': form}
    return render(request, template_name, context)

class Upload(CreateView):
    model = Inscricao
    template_name = 'documento_form.html'
    form_class = InscricaoForm


class ProdutoCreate(CreateView):
    model = Inscricao
    template_name = 'documento_form.html'
    form_class = InscricaoForm


class ProdutoUpdate(UpdateView):
    model = Inscricao
    template_name = 'documento_form.html'
    form_class = InscricaoForm



class ProdutoNotaUpdate(UpdateView):
    model = Inscricao
    template_name = 'documento_form_nota.html'
    form_class = InscricaoNotaForm


def produto_json(request, pk):
    inscricao = Inscricao.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in inscricao]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        nome = item.get('nome')
        cpf = str(item.get('cpf'))
        aprovado = True if item.get('aprovado') == 'True' else False
        email = item.get('email')

        obj = Inscricao(
            nome=nome,
            cpf=cpf,
            aprovado=aprovado,
            email=email,
        )
        aux.append(obj)
    Inscricao.objects.bulk_create(aux)


class PdfDebug(TemplateView):
    template_name = 'list_pdf.html'


"""AVISOS"""


class ListaAvisosView(ListView):
    model = FimInscricoes
    template_name = 'aviso_list.html'
    context_object_name = 'avisos'

class AvisoCreate(CreateView):
    model = FimInscricoes
    template_name = 'aviso_form.html'
    form_class = AvisoForm


class AvisoUpdate(UpdateView):
    model = FimInscricoes
    template_name = 'aviso_form.html'
    form_class = AvisoForm


class ListaAvisosView2(ListView):
    model = FimInscricoes
    template_name = 'aviso_list2.html'
    context_object_name = 'avisos'

inscricoes/templates/aviso_form.html
{% extends "base.html" %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}
{% block header %} {% endblock %}
{% block container %}

{% if user.is_authenticated %}

<a href="{% url 'core:index' %}">Voltar</a>
<form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
    <input type="hidden" name="_token" value="KqXYW17ieq2LPliZfWjnyrHlfMwZ6iQQPPglAh1k">
      <div id="inscricaoCadastro">
          <div class="row" style="padding-top: 60px;">
              <div class="col-lg-8">
                  <div class="card">
                      <div class="card-header">Avisos</div>
                        {% csrf_token %}
                        {{ form|crispy }}

                          <div class="row" style="padding-top: 30px;">
                                  <div class="col-lg-8">
                                      <!--Manter somente no modo desenvolvimento-->
                                                      <!--fim do trecho para exibir erros no registro-->
                                      <div class="form-group row">
                                          <div class="col-md-11">
                                               <a href="{% url 'inscricoes:produto_list' %}">
                                                  <button type="submit" class="btn btn-primary" id="btnContinuar" onclick="continuar(0);">
                                                      Confirmar
                                                  </button>
                                               </a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                  </div>
              </div>
          </div>
      </div>
    </input>
</form>
{% else %}
    <p3><b>ÁREA RESTRITA POR FAVOR FAÇO O LOGIN</b></p3>
      <li><a href="{% url 'login'%}?next={{request.path}}">Faça o Login</a></li>
{% endif %}
{% endblock %}

{% endblock content %}

inscricoes/templates/aviso_list.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}



  </ul>

  {% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
  {% endfor %}


  <div class="page-header">
    <a href="{% url 'core:index' %}">Voltar</a>

    <center><h2>Quadro de Avisos</h2></center>
      <span class="pull-right">
              <!--- <a target="_blank" type="button" href="{% url 'inscricoes:list_pdf' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Gerar PDF
                </button>
               </a>

                  <a target="_blank" type="button" href="{% url 'inscricoes:List_pdf_debug' %}">
                     <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> PDF debug
                    </button>
                  </a>-->

      </span>


    {% if object_list %}

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nº</th>
            <th>Aviso</th>
            <th>Situação das Incirções</th>

          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                {{ object.id }}
              </td>
              <td>
                <a href="{% url 'inscricoes:aviso_edit' object.id %}">{{ object.aviso }}</a>
              </td>
                <td>
                {% if object.fim_inscricao %}
                  <p>Encerradas</p>
                {% else %}
                   <p>Abertas</p>
                {% endif %}
              </td>

          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}

  </div>


  {% include "includes/pagination.html" %}

    {% else %}
    <p3><b>ÁREA RESTRITA POR FAVOR FAÇO O LOGIN</b></p3>
      <li><a href="{% url 'login'%}?next={{request.path}}">Faça o Login</a></li>
    {% endif %}

{% endblock content %}

{% block js %}


  <script>
    // Close alert after 2 seconds
    window.setTimeout(function() {
      $('.alert').fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 2000);
  </script>

{% endblock js %}

inscricoes/templates/aviso_list2.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'inscricoes:produto_add' %}">Voltar</a>
  </ul>

  {% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
  {% endfor %}


  <div class="page-header">

    <center><h2>Quadro de Avisos</h2></center>
      <span class="pull-right">
              <!--- <a target="_blank" type="button" href="{% url 'inscricoes:list_pdf' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Gerar PDF
                </button>
               </a>

                  <a target="_blank" type="button" href="{% url 'inscricoes:List_pdf_debug' %}">
                     <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> PDF debug
                    </button>
                  </a>-->

      </span>


    {% if object_list %}

      <table class="table table-striped">
        <thead>

        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
               <h2><center>{{ object.aviso }}</center></h2>
              </td>

          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}

  </div>


  {% include "includes/pagination.html" %}


{% endblock content %}

{% block js %}


  <script>
    // Close alert after 2 seconds
    window.setTimeout(function() {
      $('.alert').fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 2000);
  </script>

{% endblock js %}

inscricoes/templates/documento_form.html
{% extends "base.html" %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}
{% block header %} {% endblock %}
{% block container %}

<form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
    <input type="hidden" name="_token" value="KqXYW17ieq2LPliZfWjnyrHlfMwZ6iQQPPglAh1k">
      <div id="inscricaoCadastro">
          <div class="row" style="padding-top: 60px;">
              <div class="col-lg-8">
                  <div class="card">
                      <div class="card-header">Cadastrar Candidato</div>
                        {% csrf_token %}
                        {{ form|crispy }}

                          <div class="row" style="padding-top: 30px;">
                                  <div class="col-lg-8">
                                      <!--Manter somente no modo desenvolvimento-->
                                                      <!--fim do trecho para exibir erros no registro-->
                                      <div class="form-group row">
                                          <div class="col-md-11">
                                              <button type="submit" class="btn btn-primary" id="btnContinuar" onclick="continuar(0);">
                                                  Confirmar
                                              </button>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                  </div>
              </div>
          </div>
      </div>
    </input>
</form>
{% endblock %}

{% endblock content %}

inscricoes/templates/documento_form_nota.html
{% extends "base.html" %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}
{% block header %} {% endblock %}
{% block container %}

{% if user.is_authenticated %}

<a href="{% url 'core:index' %}">Voltar</a>
    <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        <input type="hidden" name="_token" value="KqXYW17ieq2LPliZfWjnyrHlfMwZ6iQQPPglAh1k">
          <div id="inscricaoCadastro">
              <div class="row" style="padding-top: 60px;">
                  <div class="col-lg-8">
                      <div class="card">
                          <div class="card-header">Cadastrar Candidato</div>
                            {% csrf_token %}
                            {{ form|crispy }}


                                  <div class="row" style="padding-top: 30px;">
                                      <div class="col-lg-8">
                                          <div class="form-group row">
                                              <div class="col-md-11">
                                                  <a href="{% url 'inscricoes:produto_list'%}"><button type="submit" class="btn btn-primary" id="btnContinuar" onclick="continuar(0);" >
                                                          Confirmar
                                                      </button>
                                                  </a>

                                              </div>
                                          </div>
                                      </div>
                                  </div>

                      </div>
                  </div>
              </div>
          </div>
        </input>
    </form>
{% else %}
        <p3><b>ÁREA RESTRITA POR FAVOR FAÇO O LOGIN</b></p3>
          <li><a href="{% url 'login'%}?next={{request.path}}">Faça o Login</a></li>
{% endif %}
{% endblock %}

{% endblock content %}

inscricoes/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}



  <center><h1>{{ object }}
    <span class="pull-right">

        <!--- <a target="_blank" type="button" href="{% url 'inscricoes:list_pdf' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Gerar PDF
                </button>
               </a>

                  <a target="_blank" type="button" href="{% url 'inscricoes:List_pdf_debug' %}">
                     <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> PDF debug
                    </button>
                  </a>-->
    </span>
  </h1></center>



    <div class="card ">
      <div class="card-header">
       <center><b>Nº de inscrição: {{ object.id }}-{{ object.cpf }}</b> </center>
      </div>
      <div class="card-body">
        <center><h5 class="card-title">Informações do Candidato</h5></center>
        <b><tbody>

            <tr>
              <th>Nome:</th>
              <td>{{ object.nome }}</td>
            </tr>
            <br>
            <br>
            <tr>
              <th>CPF:</th>
              <td>{{ object.cpf }}</td>
            </tr>
            <br>
            <br>
            <tr>
              <th >E-mail:</th>
              <td>{{ object.email }}</td>
            </tr>
            <br>
            <br>
            <tr>
              <th >Telefone:</th>
              <td>{{ object.telefone }}</td>
            <tr>
              <br>
              <br>
              <th >Endereço:</th>
              <td>{{ object.endereco }}, Nº {{ object.numero}} - {{ object.cidade }}/{{ object.estado }} - {{ object.cep }}</td>
            </tr>
            <br>
            <br>
            <tr>
              <th >Data de Nascimento:</th>
              <td>{{ object.data_nascimento }}</td>
            <tr>
              <br>
              <br>
            <tr>
              <th >Documentos:</th>
              <td>{{ object.upload }}</td>
            <tr>
          </tbody></b>

      </div>
      <div class="card-footer text-muted">
        <a href="{% url 'inscricoes:produto_edit' object.pk %}">
            <button type="button" class="btn btn-success">
              <span class="fa fa-pencil"></span> Editar
            </button>
          </a>
      </div>
    </div>







{% endblock content %}

inscricoes/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <div class="news">
        <div class="container">

  <form method="POST" >
    <input type="hidden" name="_token" value="KqXYW17ieq2LPliZfWjnyrHlfMwZ6iQQPPglAh1k">
      <div id="inscricaoCadastro">
          <div class="row" style="padding-top: 60px;">
              <div class="col-lg-8">
                  <div class="card">
                      <div class="card-header">Cadastrar Candidato</div>
                          {% csrf_token %}
                          {% for field in form.visible_fields %}
                     <div class="col-md-9">
                            <div class="form-group{% if field.errors %} has-error {% endif%}">
                              <label for="{{ field.id_for_label }}">
                                {% if field.field.required %}
                                  <span class="required">{{ field.label }} </span>
                                {% else %}
                                  {{ field.label }}
                                {% endif %}
                              </label>
                              {% render_field field class="form-control" %}
                              {% for error in field.errors %}
                                <span class="text-muted">{{ error }}</span>

                              {% endfor %}
                            </div>
                     </div>
                          {% endfor %}


              </div>
            </div>
        </div>
      </div>
                        {% if object %}
                            <a href="{% url 'inscricoes:upload' object.id %}" class="btn btn-success">
                                Adicionar documento
                            </a>
                        {% endif %}
                          <div class="row" style="padding-top: 30px;">
                              <div class="col-lg-8">
                                  <!--Manter somente no modo desenvolvimento-->
                                                  <!--fim do trecho para exibir erros no registro-->
                                  <div class="form-group row">
                                      <div class="col-md-11">
                                          <button type="submit" class="btn btn-primary" id="btnContinuar" onclick="continuar(0);">
                                              Confirmar
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>




</form>



{% endblock content %}

{% block js %}

  <script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

inscricoes/templates/produto_form2.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <form method="POST" novalidate>
    {% csrf_token %}

    <div class="form-group">
      <label for="id_importado">

        Situação

      </label>
      <input type="checkbox" name="aprovado" class="form-control" id="id_importado">

    </div>

    <div class="form-group">
      <label for="id_nome">

        <span class="required">Nome </span>

      </label>
      <input type="text" name="nome" maxlength="8" class="form-control" required id="id_nome">

    </div>

    <div class="form-group">
      <label for="id_cpf">

        <span class="required">CPF </span>

      </label>
      <input type="text" name="cpf" maxlength="100" class="form-control" required id="id_cpf">

    </div>

     <div class="form-group">
      <label for="id_email">

        <span class="required">E-mail </span>

      </label>
      <input type="text" name="nome" maxlength="8" class="form-control" required id="id_email">

    </div>

    <div class="form-group">
      <label for="id_data">

        Data

      </label>
      <input type="text" name="data" class="form-control" id="id_data">

    </div>
    </div>

     <div class="form-group">
      <label for="id_email">

        <span class="required">Documentos</span>

      </label>
      <input type="text" name="upload" maxlength="8" class="form-control" required id="id_upload">

    </div>
                {% if object.fim_inscricao %}
                  <p>Encerradas</p>
                {% else %}
                   <button type="submit" class="btn btn-success">Cadastrar</button>
                {% endif %}


  </form>

{% endblock content %}

{% block js %}

  <script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

inscricoes/templates/produto_list.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}

<a href="{% url 'core:index' %}">Voltar</a>
<br>
  </ul>

  {% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
  {% endfor %}


  <div class="page-header">
    <h2><center>Lista de Inscritos</center>
      <span class="pull-right">
              <a target="_blank" href="{% url 'inscricoes:produto_add' %}">
                  <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Adicionar
                  </button>
              </a>
              <!--- <a target="_blank" type="button" href="{% url 'inscricoes:list_pdf' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Gerar PDF
                </button>
               </a>

                  <a target="_blank" type="button" href="{% url 'inscricoes:List_pdf_debug' %}">
                     <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span> PDF debug
                    </button>
                  </a>-->

      </span>
        <div class="row">
            <div class="col-sm-6">
              <form action="." method="GET" class="form-inline">
                <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
                <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
              </form>
            </div>
        </div>
    </h2>
      <br>


    {% if object_list %}

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nº</th>
            <th>Nome</th>
            <th>CPF</th>
            <th>TELEFONE</th>
            <th>Email</th>
            <th>Nota</th>
            <th>Situação</th>

          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>
                {{ object.id }}
              </td>
              <td>
                <a  href="{% url 'inscricoes:produto_edit_nota' object.id %}">{{ object.nome }}</a>
              </td>
               <td>
                {{ object.cpf }}
              </td>
              <td>
              {{ object.telefone }}
              </td>
              <td>
                {{ object.email }}
              </td>
              <td>
                  {% if object.nota  %}

                      <center>  {{ object.nota }} </center>

                  {% else %}
                    <center><b>-</b> </center>

                  {% endif %}
              </td>
                  <td>
                  {% if object.nota == 6  %}

                      <center>  <b>Aprovado</b> </center>

                  {% elif not object.nota  %}

                      <center> <b>-</b> </center>

                  {% elif object.nota > 6  %}

                      <center>  <b>Aprovado</b> </center>

                  {% else %}
                    <center> <font color="#AA0000"><b>Reprovado</b></font></center>

                  {% endif %}
              </td>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}

  </div>


  {% include "includes/pagination.html" %}

    {% else %}
    <p3><b>ÁREA RESTRITA POR FAVOR FAÇO O LOGIN</b></p3>
      <li><a href="{% url 'login'%}?next={{request.path}}">Faça o Login</a></li>
    {% endif %}

{% endblock content %}

{% block js %}


  <script>
    // Close alert after 2 seconds
    window.setTimeout(function() {
      $('.alert').fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 2000);
  </script>

{% endblock js %}