core/urls.py
from django.urls import path

from core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

inscricoes/urls.py
from django.urls import path


from inscricoes import views as v

app_name = 'inscricoes'


urlpatterns = [
    path('', v.InscricaoList.as_view(), name='produto_list'),
    path('listpdf/', v.GeneratePDF.as_view(), name='list_pdf'),
    path('List_pdf_debug', v.PdfDebug.as_view(), name='List_pdf_debug'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('<int:pk>/upload/', v.Upload.as_view(), name='upload'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('add2/', v.produto_add, name='produto_add2'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/nota/', v.ProdutoNotaUpdate.as_view(), name='produto_edit_nota'),

    path('<int:pk>/json/', v.produto_json, name='produto_json'),

    path('avisolista', v.ListaAvisosView.as_view(), name='aviso_list'),
    path('aviso_add/', v.AvisoCreate.as_view(), name='aviso_add'),
    path('<int:pk>/edit_aviso/', v.AvisoUpdate.as_view(), name='aviso_edit'),
    path('avisolista2', v.ListaAvisosView2.as_view(), name='aviso_list2'),

]

inscricoes_ex/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

@login_required(login_url='login/')
def index(request):
    return render(request, 'index.html')

"""def index(request):
    return render(request, 'index.html')"""

core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

    <head>
      <style type="text/css">
                  body {
            margin-top: 60px;
          }

          .ok {
            color: green;
          }

          .no {
            color: red;
          }

          span.required:after {
            content: "*";
            color: red;
          }

          body, html {
              height: 100%;
              background-repeat: no-repeat;

          }

          .card-container.card {
              max-width: 350px;
              padding: 40px 40px;
          }

          .btn {
              font-weight: 700;
              height: 36px;
              -moz-user-select: none;
              -webkit-user-select: none;
              user-select: none;
              cursor: default;
          }

          /*
           * Card component
           */
          .card {
              background-color: #F7F7F7;
              /* just in case there no content*/
              padding: 20px 25px 30px;
              margin: 0 auto 25px;
              margin-top: 50px;
              /* shadows and rounded borders */
              -moz-border-radius: 2px;
              -webkit-border-radius: 2px;
              border-radius: 2px;
              -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
              -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
              box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
          }

          .profile-img-card {
              width: 96px;
              height: 96px;
              margin: 0 auto 10px;
              display: block;
              -moz-border-radius: 50%;
              -webkit-border-radius: 50%;
              border-radius: 50%;
          }

          /*
           * Form styles
           */
          .profile-name-card {
              font-size: 16px;
              font-weight: bold;
              text-align: center;
              margin: 10px 0 0;
              min-height: 1em;
          }

          .reauth-email {
              display: block;
              color: #404040;
              line-height: 2;
              margin-bottom: 10px;
              font-size: 14px;
              text-align: center;
              overflow: hidden;
              text-overflow: ellipsis;
              white-space: nowrap;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
          }

          .form-signin #inputEmail,
          .form-signin #inputPassword {
              direction: ltr;
              height: 44px;
              font-size: 16px;
          }

          .form-signin input[type=email],
          .form-signin input[type=password],
          .form-signin input[type=text],
          .form-signin button {
              width: 100%;
              display: block;
              margin-bottom: 10px;
              z-index: 1;
              position: relative;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
          }

          .form-signin .form-control:focus {
              border-color: rgb(104, 145, 162);
              outline: 0;
              -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
              box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
          }

          .btn.btn-signin {
              /*background-color: #4d90fe; */
              background-color: rgb(104, 145, 162);
              /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
              padding: 0px;
              font-weight: 700;
              font-size: 14px;
              height: 36px;
              -moz-border-radius: 3px;
              -webkit-border-radius: 3px;
              border-radius: 3px;
              border: none;
              -o-transition: all 0.218s;
              -moz-transition: all 0.218s;
              -webkit-transition: all 0.218s;
              transition: all 0.218s;
          }

          .btn.btn-signin:hover,
          .btn.btn-signin:active,
          .btn.btn-signin:focus {
              background-color: rgb(12, 97, 33);
          }

          .forgot-password {
              color: rgb(104, 145, 162);
          }

          .forgot-password:hover,
          .forgot-password:active,
          .forgot-password:focus{
              color: rgb(12, 97, 33);
          }
      </style>
    </head>



    {% block css %}{% endblock css %}

  </head>
  <body>

    {% include "includes/nav.html" %}

    <div class="container">
      {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>

    img {
  width: 100px;
  }
</style>


<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div class="jumbotron">
      <div class="container">
        <div class="container">
            <center><img src="{% static 'img/logoex.png' %}"  /></center>
        </div>

        <center><h1>Área do Administrador</h1></center>

        <br>
        <br>


        <center>
                  <a href="{% url 'inscricoes:produto_list'%}">
                    <button type="button" class="btn btn-primary">
                        Inscritos <span class="badge badge-light">{{object.count}}</span>
                    </button>
                  </a>

              <a href="{% url 'inscricoes:aviso_list' %}">
                <button type="button" class="btn btn-success"> Avisos  </button>
              </a>
        </center>

      </div>
    </div>
  </header>
</div>

{% endblock content %}